// Bem-vindo ao modo de exibição de consulta DAX! Saiba mais sobre consultas DAX em https://aka.ms/dax-queries.
// Clique com o botão direito do mouse em tabelas, colunas ou medidas no painel de dados para acessar consultas rápidas ou peça ajuda ao Copilot para escrever DAX.

// Selecione "Executar" para experimentar esta consulta DAX de exemplo.
EVALUATE
{
MAXX(
    FILTER(
        ADDCOLUMNS(
            VALUES(fPedido[empresa]),
            "NoFillRateEmpresa", 
            [Qtde Linhas NO-FILL_RATE],
            "Ranking", 
            RANKX(
                VALUES(fPedido[empresa]),
                [Qtde Linhas NO-FILL_RATE],
                , DESC
            )
        ),
        [Ranking] = 1
    ),
    fPedido[empresa]
)}