table _Medidas
	lineageTag: 129502df-8550-4b7d-a314-0d34a45134ec

	measure 'Qtde Total de Linhas' = COUNTROWS(fPedido)
		formatString: #,0
		displayFolder: OTIF\LINHA
		lineageTag: 06a172ae-b489-4675-a31c-656065997023

	measure 'Qtde Linhas OTIF' =
			
			CALCULATE(
			    [Qtde Total de Linhas],
			    fPedido[@OTIF Linha] = "OTIF"
			)
		formatString: #,0
		displayFolder: OTIF\LINHA
		lineageTag: 65fa613f-d3c9-4fb9-b34a-10d9f780b339

	measure 'Qtde Linhas NO-OTIF' =
			
			CALCULATE(
			    [Qtde Total de Linhas],
			    fPedido[@OTIF Linha] = "NO-OTIF"
			)
		formatString: #,0
		displayFolder: OTIF\LINHA
		lineageTag: 34640daf-1c84-429e-b7a6-92a1d99d642e

	measure 'Qtde Linhas Ainda No Prazo' =
			
			CALCULATE(
			    [Qtde Total de Linhas],
			    fPedido[@OTIF Linha] = "Ainda No Prazo"
			)
		formatString: #,0
		displayFolder: OTIF\LINHA
		lineageTag: 4b27f5dd-e6ad-4942-b521-6d8e291681ca

	measure '% OTIF' = DIVIDE([Qtde Linhas OTIF], [Qtde Total de Linhas], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OTIF\LINHA
		lineageTag: 2b3046ff-ad16-44af-bc6c-55e71fab0f88

	measure '% NO-OTIF' = DIVIDE([Qtde Linhas NO-OTIF], [Qtde Total de Linhas], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OTIF\LINHA
		lineageTag: dab40cac-85e5-44d1-855b-5a170560e575

	measure '% Ainda No Prazo' = DIVIDE([Qtde Linhas Ainda No Prazo], [Qtde Total de Linhas], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OTIF\LINHA
		lineageTag: ca46dd1d-1650-4f8d-862b-2f63e1bbfbf4

	measure '(R$) Total Pedidos' = SUMX(fPedido, fPedido[PRECO_UNIT] * fPedido[QTDE])
		formatString: "R$"#,0;-"R$"#,0;"R$"#,0
		displayFolder: OTIF
		lineageTag: b55c16dc-c2de-46ca-8a79-30457bcbb7f6

		annotation PBI_FormatHint = {"currencyCulture":"es-BR"}

	measure 'Qtde Pedidos OTIF' =
			
			CALCULATE(
			    [Qtde Total de Pedidos],
			    AnaliseOTIFpedido[@OTIF Pedido] = "OTIF"
			)
		formatString: #,0
		displayFolder: OTIF\PEDIDO
		lineageTag: a1b2c3d4-e5f6-4g7h-8i9j-0k1l2m3n4o5p

	measure 'Qtde Pedidos NO-OTIF' =
			
			CALCULATE(
			    [Qtde Total de Pedidos],
			    AnaliseOTIFpedido[@OTIF Pedido] = "NO-OTIF"
			)
		formatString: #,0
		displayFolder: OTIF\PEDIDO
		lineageTag: b2c3d4e5-f6g7-4h8i-9j0k-1l2m3n4o5p6q

	measure 'Qtde Total de Pedidos' = COUNTROWS(AnaliseOTIFpedido)
		formatString: 0
		displayFolder: OTIF\PEDIDO
		lineageTag: 8ddd241f-0937-4b5e-a290-eef257243459

	measure 'Qtde Pedidos Ainda No Prazo' =
			
			CALCULATE(
			    [Qtde Total de Pedidos],
			    AnaliseOTIFpedido[@OTIF Pedido] = "Ainda No Prazo"
			)
		formatString: #,0
		displayFolder: OTIF\PEDIDO
		lineageTag: 92ba4434-6b79-446f-9182-377737419128

	measure '% OTIF PEDIDO' =
			
			DIVIDE([Qtde Pedidos OTIF], [Qtde Total de Pedidos], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OTIF\PEDIDO
		lineageTag: 7380af43-fd1e-432a-a970-6f489f640ab7

	measure '% NO-OTIF PEDIDO' =
			
			DIVIDE([Qtde Pedidos NO-OTIF], [Qtde Total de Pedidos], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OTIF\PEDIDO
		lineageTag: eecd8fa8-03aa-4b9e-8a9c-1dc51faf25e3

	measure '% Ainda No Prazo Pedido' =
			
			DIVIDE([Qtde Pedidos Ainda No Prazo], [Qtde Total de Pedidos], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OTIF\PEDIDO
		lineageTag: 33fc3220-bb82-4da3-8e16-1697aab5e41a

	column Value
		isHidden
		formatString: 0
		lineageTag: 3ccd33d6-dbec-48e1-ba6a-ea58f7fbfd44
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 5ae64b622b7948ac8a958c62722aa216

