table fPedido
	lineageTag: 8d1d4e16-a9fc-496f-85f3-98825f614213

	column NR_PEDIDO
		dataType: string
		lineageTag: a3e68213-6c70-4b65-8abc-2da20dda9c8f
		summarizeBy: none
		sourceColumn: NR_PEDIDO

		annotation SummarizationSetBy = Automatic

	column DT_EMISSAO
		dataType: dateTime
		formatString: Short Date
		lineageTag: 05efa664-fc3f-43a2-95f6-f0a6df15260e
		summarizeBy: none
		sourceColumn: DT_EMISSAO

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column POS_PDV
		dataType: string
		lineageTag: 17308021-2867-44a3-9b6b-b14e0b205567
		summarizeBy: none
		sourceColumn: POS_PDV

		annotation SummarizationSetBy = Automatic

	column QTDE
		dataType: double
		lineageTag: 7f94f909-dd7b-4179-8013-0ef7099003d0
		summarizeBy: sum
		sourceColumn: QTDE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDE_ATEND
		dataType: double
		lineageTag: 7bc24213-72c2-47eb-a25b-6b0fa3c432de
		summarizeBy: sum
		sourceColumn: QTDE_ATEND

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLR_BRUTO
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 6bc489c5-645d-4904-b751-e21b8ee88e51
		summarizeBy: sum
		sourceColumn: VLR_BRUTO

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DT_ENTREGA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7b9d6070-1e2c-4308-acb5-d3d2278b0593
		summarizeBy: none
		sourceColumn: DT_ENTREGA

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NF_DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9adc8c52-1451-4cc8-bc1b-356c4a696b0c
		summarizeBy: none
		sourceColumn: NF_DATA

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PRIORIDADE
		dataType: string
		lineageTag: 0d980689-cac9-4056-959a-f27109107695
		summarizeBy: none
		sourceColumn: PRIORIDADE

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_PED
		dataType: int64
		formatString: 0
		lineageTag: 2462aa95-0935-40af-bf3d-59993bd0e743
		summarizeBy: sum
		sourceColumn: NR_SEQ_PED

		annotation SummarizationSetBy = Automatic

	column '@OTIF Linha' = ```
			
			 //Caso tenha nota fiscal com a data igual ou anterior a data prometida na linha do pedido, então é OTIF.
			 //Se não tiver data da nota após data prometida do cliente ou nota tiver sido emitida depois da data prometida para o cliente é NO-OTIF
			 //Se não tiver nota fiscal, mas ainda estiver dentro do prazo prometido para o cliente deixar em branco.
			VAR _DiferencaPrevistoHoje = DATEDIFF(fPedido[DT_ENTREGA], TODAY(), DAY)
			VAR _DiferencaPrevistoNota = DATEDIFF(fPedido[DT_ENTREGA], fPedido[NF_DATA], DAY)
			VAR _NotaEmBranco = IF(ISBLANK(fPedido[NF_DATA]), "Sim", "Não")
			VAR _Conta =
			SWITCH(TRUE(),
			        _DiferencaPrevistoHoje <= 0 && _NotaEmBranco = "Sim", "Ainda No Prazo",
			        _DiferencaPrevistoHoje > 0 && _NotaEmBranco = "Sim", "NO-OTIF",
			        _DiferencaPrevistoNota > 0, "NO-OTIF",
			        _DiferencaPrevistoNota <= 0, "OTIF",
			        BLANK()
			    )
			RETURN _Conta
			```
		lineageTag: 658073b0-94b6-4151-b9c7-884a4f86bd3f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PRECO_UNIT
		dataType: double
		lineageTag: 1070c272-e90b-4466-9cd3-9bd04a755140
		summarizeBy: sum
		sourceColumn: PRECO_UNIT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NF_SERIE
		dataType: string
		lineageTag: dcf7cc20-8abc-4b37-abe9-27e32c9d0d88
		summarizeBy: none
		sourceColumn: NF_SERIE

		annotation SummarizationSetBy = Automatic

	column NF_NUM
		dataType: string
		lineageTag: 2a312dc1-f0ca-4075-bf2d-e8ac94d1a9a6
		summarizeBy: none
		sourceColumn: NF_NUM

		annotation SummarizationSetBy = Automatic

	column IdPedidoSaldoEstoque
		dataType: string
		lineageTag: 95c34afc-9c2d-4905-93b6-b139454c30d2
		summarizeBy: none
		sourceColumn: IdPedidoSaldoEstoque

		annotation SummarizationSetBy = Automatic

	column '@Qtde Estoque No Dia' = ```
			
			VAR _MaxDate =
			    CALCULATE (
			        MAX ( dSaldoEstoqueDiario[periodo] ),
			        FILTER (
			            dSaldoEstoqueDiario,
			            dSaldoEstoqueDiario[periodo] <= fPedido[DT_EMISSAO]
			        )
			    )
			VAR _Conta = CALCULATE (
			        SUM ( dSaldoEstoqueDiario[Quantidade] ),
			        FILTER (
			            dSaldoEstoqueDiario,
			            dSaldoEstoqueDiario[periodo] = (_MaxDate) 
			        )
			    )
			RETURN
			_Conta
			
			```
		formatString: #,0.00
		lineageTag: cb817b6e-4450-4c56-ab09-eb750236d745
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '@FILL RATE Linha' =
			
			IF( fPedido[@Qtde Estoque No Dia] > 0 && fPedido[@Qtde Estoque No Dia] >= fPedido[QTDE_EM_ABERTO], "FILL_RATE","NO-FILL_RATE")
		lineageTag: 15b66fa3-6c84-4314-a29c-43b52512f92c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column QTDE_EM_ABERTO
		dataType: double
		lineageTag: c5bd45a2-90f9-4537-b7b8-17fb51d60de9
		summarizeBy: sum
		sourceColumn: QTDE_EM_ABERTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_PEDIDO_SEQ_ITEM
		dataType: string
		lineageTag: 39b0db00-eb45-4f48-b88f-a7a7a0be6cee
		summarizeBy: none
		sourceColumn: ID_PEDIDO_SEQ_ITEM

		annotation SummarizationSetBy = Automatic

	column @Observacao = RELATED(fBaseCarteira[Observacao])
		lineageTag: 3d479ce8-d831-4a7a-8f91-aabce230384f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column @StatusBI = RELATED(fBaseCarteira[STATUS_BI])
		lineageTag: 41db5d90-1a04-444c-9ab0-8cd228860bcb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CLIENTE
		dataType: string
		lineageTag: 0be744ba-414e-4bd2-87c5-16109b438df6
		summarizeBy: none
		sourceColumn: CLIENTE

		annotation SummarizationSetBy = Automatic

	column FAMILIA_COMERCIAL
		dataType: string
		lineageTag: f8dd2d2c-382d-442b-b2ff-a721ffd5db2c
		summarizeBy: none
		sourceColumn: FAMILIA_COMERCIAL

		annotation SummarizationSetBy = Automatic

	column EMPRESA
		dataType: string
		lineageTag: 155a4881-247c-4736-a6e0-509367c7d0de
		summarizeBy: none
		sourceColumn: EMPRESA

		annotation SummarizationSetBy = Automatic

	column REPRESENTANTE
		dataType: string
		lineageTag: cb396e71-d561-4648-9748-eda261e4a1bd
		summarizeBy: none
		sourceColumn: REPRESENTANTE

		annotation SummarizationSetBy = Automatic

	column DIM_ITEM_ID
		dataType: string
		lineageTag: 9021a134-cc62-4282-b671-d8d76bfb5295
		summarizeBy: none
		sourceColumn: DIM_ITEM_ID

		annotation SummarizationSetBy = Automatic

	column '@Categoria Valor Pedido' = ```
			
			VAR _CategoriaValor = 
			SWITCH(TRUE(),
			    fPedido[VLR_BRUTO] <= 500, "Baixo Valor (≤R$500)",
			    fPedido[VLR_BRUTO] <= 2000, "Valor Médio (R$501-2.000)",
			    fPedido[VLR_BRUTO] <= 5000, "Alto Valor (R$2.001-5.000)",
			    fPedido[VLR_BRUTO] <= 15000, "Valor Premium (R$5.001-15.000)",
			    fPedido[VLR_BRUTO] > 15000, "Valor Crítico (>R$15.000)",
			    "Valor Não Informado"
			)
			
			RETURN _CategoriaValor
			```
		lineageTag: af1a5f78-e4f9-4d0f-bf8f-4f6f7a8b9cae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '@Status Estoque' = ```
			
			VAR _EstoqueDisponivel = fPedido[@Qtde Estoque No Dia]
			VAR _QtdeSolicitada = fPedido[QTDE_EM_ABERTO]
			VAR _PercentualAtendimento = DIVIDE(_EstoqueDisponivel, _QtdeSolicitada, 0)
			
			VAR _StatusEstoque = 
			SWITCH(TRUE(),
			    ISBLANK(_EstoqueDisponivel) || _EstoqueDisponivel = 0, "Sem Estoque",
			    _PercentualAtendimento >= 1, "Estoque Suficiente",
			    _PercentualAtendimento >= 0.8, "Estoque Parcial (80-99%)",
			    _PercentualAtendimento >= 0.5, "Estoque Limitado (50-79%)",
			    _PercentualAtendimento > 0, "Estoque Crítico (<50%)",
			    _QtdeSolicitada = 0, "Linha Atendida",
			    "Não Verificado"
			)
			
			RETURN _StatusEstoque
			```
		lineageTag: bf2a6f89-f5fa-4e0f-cf9f-5f7f8a9bacbf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '@Tipo Cliente' = ```
			
			VAR _Cliente = fPedido[CLIENTE]
			VAR _ValorTotal = fPedido[VLR_BRUTO]
			VAR _TotalPedidosCliente = CALCULATE(
			    COUNTROWS(fPedido),
			    ALLEXCEPT(fPedido, fPedido[CLIENTE])
			)
			
			VAR _TipoCliente = 
			SWITCH(TRUE(),
			    _TotalPedidosCliente >= 100 && _ValorTotal >= 5000, "Cliente VIP",
			    _TotalPedidosCliente >= 50 && _ValorTotal >= 2000, "Cliente Premium",
			    _TotalPedidosCliente >= 20, "Cliente Frequente",
			    _TotalPedidosCliente >= 5, "Cliente Regular",
			    _TotalPedidosCliente < 5, "Cliente Novo/Esporádico",
			    "Não Classificado"
			)
			
			RETURN _TipoCliente
			```
		lineageTag: df4a8fab-17fc-4g2f-ef1f-7f9faabbccdf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column REGIONAL
		dataType: string
		lineageTag: f1cfe4af-bbdb-4105-ade7-6aff8f5314fe
		summarizeBy: none
		sourceColumn: REGIONAL

		annotation SummarizationSetBy = Automatic

	column '@Faixa Qtde Itens Pedido' = ```
			
			VAR _QtdItens = CALCULATE(
			    DISTINCTCOUNT(fPedido[DIM_ITEM_ID]),
			    ALLEXCEPT(fPedido, fPedido[NR_PEDIDO])
			)
			
			VAR _Faixa = SWITCH(TRUE(),
			    _QtdItens = 1, "Item Único",
			    _QtdItens <= 8, "Pedido Pequeno (2-8 itens)",
			    _QtdItens <= 19, "Pedido Médio (9-19 itens)",
			    _QtdItens <= 550, "Pedido Grande (20-550 itens)",
			    _QtdItens > 551, "Pedido Complexo (+551 itens)",
			    "Não Classificado"
			)
			RETURN _Faixa
			
			```
		lineageTag: 77711844-494f-4880-9022-411b236f7591
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '@Estoque Ou Já Pode Atender' =
			
			IF(fPedido[@StatusBI] = "Já Pode Aender" || fPedido[@Status Estoque] = "Estoque Suficiente", "Atendimento Imediato", "Sem Atendimento Imediato")
		lineageTag: e8839c39-d1e9-4e00-9ed6-13386e567339
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '@Qtde Dias Desde Criação' = DATEDIFF(fPedido[DT_EMISSAO], TODAY(), DAY)
		formatString: 0
		lineageTag: eecff70d-aa31-43e6-9506-8e0417a8d560
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fPedido-24034e89-6c6d-42ea-a97d-3af7c3cf61e1 = m
		mode: import
		source =
				let
				    // Fonte de dados principal com seleção otimizada de colunas
				    Fonte = Sql.Database("BRPIN-DBS008\PowerBI", "idba_komatsu", [Query="
				    -- ETL Otimizado: Seleção apenas de colunas utilizadas em visuais, medidas e relacionamentos
				    SELECT
				          -- Identificadores principais (chaves e relacionamentos)
				          A.NR_PEDIDO,                                          -- Chave para relacionamentos OTIF/FILL_RATE
				          CONCAT(A.NR_PEDIDO_CLIENTE, '-', A.NR_SEQ_PED,'-', A.DIM_ITEM_ID) AS ID_PEDIDO_SEQ_ITEM, -- Chave para fBaseCarteira
				          CONCAT(A.DIM_EMPRESA_ID, '_', A.DIM_ITEM_ID) AS IdPedidoSaldoEstoque,                    -- Chave para dSaldoEstoqueDiario
				
				          -- Datas (críticas para OTIF)
				          A.DT_EMISSAO,                                         -- Relacionamento com dCalendario
				          A.DT_ENTREGA,                                         -- Prazo prometido (essencial para OTIF)
				          A.NF_DATA,                                            -- Data entrega real (essencial para OTIF)
				
				          -- Quantidades (essenciais para Fill Rate)
				          A.QTDE,                                               -- Quantidade solicitada
				          A.QTDE_ATEND,                                         -- Quantidade já atendida
				          A.QTDE - A.QTDE_ATEND AS QTDE_EM_ABERTO,             -- Quantidade pendente (crítica para Fill Rate)
				
				          -- Valores financeiros
				          A.PRECO_UNIT,                                         -- Para cálculos de valor total
				          A.VLR_BRUTO,                                          -- Para categorização por valor
				
				          -- Dimensões analíticas utilizadas em visuais
				          CONCAT(D.COD_CLIENTE, ' - ', D.CLIENTE) AS CLIENTE,  -- Usado em slicers e análises
				          E.DESC_C1 AS FAMILIA_COMERCIAL,                      -- Segmentação de produtos
				          CONCAT(F.DIM_EMPRESA_ID, ' - ', F.CIDADE) AS EMPRESA, -- Análise por filial
				          F.REGIONAL,                                           -- Análise regional
				          CONCAT(G.COD_REPRESENTANTE, ' - ', G.REPRESENTANTE) AS REPRESENTANTE, -- Análise de vendas
				          CONCAT(E.DIM_ITEM_ID, ' - ', E.NM_ITEM) AS DIM_ITEM_ID, -- Identificação do item
				
				          -- Campos operacionais utilizados
				          A.POS_PDV,                                            -- Status operacional (filtro Cancelado)
				          A.PRIORIDADE,                                         -- Priorização de atendimento
				          A.NR_SEQ_PED,                                        -- Sequencia do item no pedido
				
				          -- Campos de Nota Fiscal (para validação OTIF)
				          A.NF_NUM,                                            -- Número da nota fiscal
				          A.NF_SERIE                                           -- Série da nota fiscal
				
				      FROM [idba_komatsu].[dbo].[FATO_PEDIDO_BI] A
				      INNER JOIN DIM_DIVISAO_VENDA_BI B ON A.DIM_DIVISAO_VENDA_ID = B.DIM_DIVISAO_VENDA_ID
				      LEFT JOIN DIM_CLIENTE_BI D ON D.COD_CLIENTE = A.DIM_CLIENTE_ID
				      LEFT JOIN DIM_ITEM_BI E ON E.CD_ITEM = A.DIM_ITEM_ID
				      LEFT JOIN DIM_EMPRESA_BI F ON F.COD_EMPRESA = A.DIM_EMPRESA_ID
				      LEFT JOIN DIM_REPRESENTANTE_BI G ON G.COD_REPRESENTANTE = A.DIM_REPRESENTANTE_ID
				
				      -- Filtros de performance e qualidade dos dados
				      WHERE B.TP_DIVISAO_VENDA IN ('PEÇAS','PEÇAS ATIVAS','PEÇAS KDB', 'PEÇAS CONTRATO')
				        AND A.POS_PDV <> 'Cancelado'                          -- Remove pedidos cancelados
				        AND A.DT_EMISSAO > '01/01/2022'                       -- Janela de análise relevante
				
				      ORDER BY A.DT_EMISSAO DESC
				    "]),
				
				    // Transformação de tipos otimizada
				    #"Tipos Convertidos" = Table.TransformColumnTypes(Fonte,{
				        {"DT_EMISSAO", type date},
				        {"DT_ENTREGA", type date},
				        {"NF_DATA", type date}
				    })
				in
				    #"Tipos Convertidos"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

