table fPedido
	lineageTag: 8d1d4e16-a9fc-496f-85f3-98825f614213

	column NR_PEDIDO
		dataType: string
		lineageTag: a3e68213-6c70-4b65-8abc-2da20dda9c8f
		summarizeBy: none
		sourceColumn: NR_PEDIDO

		annotation SummarizationSetBy = Automatic

	column DT_EMISSAO
		dataType: dateTime
		formatString: Short Date
		lineageTag: 05efa664-fc3f-43a2-95f6-f0a6df15260e
		summarizeBy: none
		sourceColumn: DT_EMISSAO

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column POS_PDV
		dataType: string
		lineageTag: 17308021-2867-44a3-9b6b-b14e0b205567
		summarizeBy: none
		sourceColumn: POS_PDV

		annotation SummarizationSetBy = Automatic

	column QTDE
		dataType: double
		lineageTag: 7f94f909-dd7b-4179-8013-0ef7099003d0
		summarizeBy: sum
		sourceColumn: QTDE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDE_ATEND
		dataType: double
		lineageTag: 7bc24213-72c2-47eb-a25b-6b0fa3c432de
		summarizeBy: sum
		sourceColumn: QTDE_ATEND

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLR_BRUTO
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 6bc489c5-645d-4904-b751-e21b8ee88e51
		summarizeBy: sum
		sourceColumn: VLR_BRUTO

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DT_ENTREGA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7b9d6070-1e2c-4308-acb5-d3d2278b0593
		summarizeBy: none
		sourceColumn: DT_ENTREGA

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DIM_DIVISAO_VENDA_ID
		dataType: string
		lineageTag: 52e57309-aec6-4411-8a17-dca4df0a86f9
		summarizeBy: none
		sourceColumn: DIM_DIVISAO_VENDA_ID

		annotation SummarizationSetBy = Automatic

	column NF_DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9adc8c52-1451-4cc8-bc1b-356c4a696b0c
		summarizeBy: none
		sourceColumn: NF_DATA

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PRIORIDADE
		dataType: string
		lineageTag: 0d980689-cac9-4056-959a-f27109107695
		summarizeBy: none
		sourceColumn: PRIORIDADE

		annotation SummarizationSetBy = Automatic

	column NR_PEDIDO_CLIENTE
		dataType: string
		lineageTag: 362afce5-080f-448c-acce-b117b784447c
		summarizeBy: none
		sourceColumn: NR_PEDIDO_CLIENTE

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_PED
		dataType: int64
		formatString: 0
		lineageTag: 2462aa95-0935-40af-bf3d-59993bd0e743
		summarizeBy: sum
		sourceColumn: NR_SEQ_PED

		annotation SummarizationSetBy = Automatic

	column TP_DIVISAO_VENDA
		dataType: string
		lineageTag: 3cf32e0c-8be3-4f81-88a8-159e55e5520e
		summarizeBy: none
		sourceColumn: TP_DIVISAO_VENDA

		annotation SummarizationSetBy = Automatic

	column '@OTIF Linha' = ```
			
			 //Caso tenha nota fiscal com a data igual ou anterior a data prometida na linha do pedido, então é OTIF.
			 //Se não tiver data da nota após data prometida do cliente ou nota tiver sido emitida depois da data prometida para o cliente é NO-OTIF
			 //Se não tiver nota fiscal, mas ainda estiver dentro do prazo prometido para o cliente deixar em branco.
			VAR _DiferencaPrevistoHoje = DATEDIFF(fPedido[DT_ENTREGA], TODAY(), DAY)
			VAR _DiferencaPrevistoNota = DATEDIFF(fPedido[DT_ENTREGA], fPedido[NF_DATA], DAY)
			VAR _NotaEmBranco = IF(ISBLANK(fPedido[NF_DATA]), "Sim", "Não")
			VAR _Conta =
			SWITCH(TRUE(),
			        _DiferencaPrevistoHoje <= 0 && _NotaEmBranco = "Sim", "Ainda No Prazo",
			        _DiferencaPrevistoHoje > 0 && _NotaEmBranco = "Sim", "NO-OTIF",
			        _DiferencaPrevistoNota > 0, "NO-OTIF",
			        _DiferencaPrevistoNota <= 0, "OTIF",
			        BLANK()
			    )
			RETURN _Conta
			```
		lineageTag: 658073b0-94b6-4151-b9c7-884a4f86bd3f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DIM_COND_PAGTO_ID
		dataType: string
		lineageTag: 749630c8-900a-479a-a67c-9780dcf2d83f
		summarizeBy: none
		sourceColumn: DIM_COND_PAGTO_ID

		annotation SummarizationSetBy = Automatic

	column TIPO
		dataType: string
		lineageTag: 917c0888-38b1-480b-b01e-e6b1c5827a60
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column QTDE_CANC
		dataType: double
		lineageTag: eeebad80-e8b1-444b-b800-b536e9eb2bf4
		summarizeBy: sum
		sourceColumn: QTDE_CANC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDE_SLDO
		dataType: double
		lineageTag: da1a80bd-28c3-4339-9707-f88996b37337
		summarizeBy: sum
		sourceColumn: QTDE_SLDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRECO_UNIT
		dataType: double
		lineageTag: 1070c272-e90b-4466-9cd3-9bd04a755140
		summarizeBy: sum
		sourceColumn: PRECO_UNIT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLR_BRUTO_SICMS
		dataType: double
		lineageTag: bdc1970d-1d32-44d6-8cc7-2acff62f66a2
		summarizeBy: sum
		sourceColumn: VLR_BRUTO_SICMS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NF_SERIE
		dataType: string
		lineageTag: dcf7cc20-8abc-4b37-abe9-27e32c9d0d88
		summarizeBy: none
		sourceColumn: NF_SERIE

		annotation SummarizationSetBy = Automatic

	column NF_NUM
		dataType: string
		lineageTag: 2a312dc1-f0ca-4075-bf2d-e8ac94d1a9a6
		summarizeBy: none
		sourceColumn: NF_NUM

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_PED_NF
		dataType: int64
		formatString: 0
		lineageTag: 7aa0ef72-609b-4b14-ad3d-7c18117d1172
		summarizeBy: sum
		sourceColumn: NR_SEQ_PED_NF

		annotation SummarizationSetBy = Automatic

	column FATURAMENTO_PARCIAL
		dataType: string
		lineageTag: 9ab96b36-fb36-4bce-bf4d-726a0d84dc93
		summarizeBy: none
		sourceColumn: FATURAMENTO_PARCIAL

		annotation SummarizationSetBy = Automatic

	column VALOR_LIQUIDO_NF
		dataType: double
		lineageTag: 4aaca924-2ba0-4169-b6a1-e629ba122f0e
		summarizeBy: sum
		sourceColumn: VALOR_LIQUIDO_NF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NM_UNID_NEGOC
		dataType: string
		lineageTag: 5ce78953-ca32-4c46-91a1-4a822fba0e66
		summarizeBy: none
		sourceColumn: NM_UNID_NEGOC

		annotation SummarizationSetBy = Automatic

	column IdPedidoSaldoEstoque
		dataType: string
		lineageTag: 95c34afc-9c2d-4905-93b6-b139454c30d2
		summarizeBy: none
		sourceColumn: IdPedidoSaldoEstoque

		annotation SummarizationSetBy = Automatic

	column '@Qtde Estoque No Dia' = ```
			
			VAR _MaxDate =
			    CALCULATE (
			        MAX ( dSaldoEstoqueDiario[periodo] ),
			        FILTER (
			            dSaldoEstoqueDiario,
			            dSaldoEstoqueDiario[periodo] <= fPedido[DT_EMISSAO]
			        )
			    )
			--VAR _PenultimaData =
			--    CALCULATE (
			--        MAX ( FSaldoEstoqueDiario[periodo] ),
			--        FILTER (
			--            FSaldoEstoqueDiario,
			--            FSaldoEstoqueDiario[cod-estabel] = fPedido[DIM_EMPRESA_ID]
			--                && FSaldoEstoqueDiario[it-codigo] = fPedido[DIM_ITEM_ID]
			--                && FSaldoEstoqueDiario[periodo] < _MaxDate
			--                && FSaldoEstoqueDiario[periodo] <= fPedido[DT_EMISSAO]
			--        )
			--    )
			VAR _Conta = CALCULATE (
			        SUM ( dSaldoEstoqueDiario[Quantidade] ),
			        FILTER (
			            dSaldoEstoqueDiario,
			            dSaldoEstoqueDiario[periodo] = (_MaxDate) 
			        )
			    )
			RETURN
			_Conta
			
			```
		formatString: #,0.00
		lineageTag: cb817b6e-4450-4c56-ab09-eb750236d745
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '@FILL RATE Linha' =
			
			IF( fPedido[@Qtde Estoque No Dia] > 0 && fPedido[@Qtde Estoque No Dia] >= fPedido[QTDE_EM_ABERTO], "FILL_RATE","NO-FILL_RATE")
		lineageTag: 15b66fa3-6c84-4314-a29c-43b52512f92c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column QTDE_EM_ABERTO
		dataType: double
		lineageTag: c5bd45a2-90f9-4537-b7b8-17fb51d60de9
		summarizeBy: sum
		sourceColumn: QTDE_EM_ABERTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_PEDIDO_SEQ_ITEM
		dataType: string
		lineageTag: 39b0db00-eb45-4f48-b88f-a7a7a0be6cee
		summarizeBy: none
		sourceColumn: ID_PEDIDO_SEQ_ITEM

		annotation SummarizationSetBy = Automatic

	column @Observacao = RELATED(fBaseCarteira[Observacao])
		lineageTag: 3d479ce8-d831-4a7a-8f91-aabce230384f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column @StatusBI = RELATED(fBaseCarteira[STATUS_BI])
		lineageTag: 41db5d90-1a04-444c-9ab0-8cd228860bcb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CLIENTE
		dataType: string
		lineageTag: 0be744ba-414e-4bd2-87c5-16109b438df6
		summarizeBy: none
		sourceColumn: CLIENTE

		annotation SummarizationSetBy = Automatic

	column FAMILIA_COMERCIAL
		dataType: string
		lineageTag: f8dd2d2c-382d-442b-b2ff-a721ffd5db2c
		summarizeBy: none
		sourceColumn: FAMILIA_COMERCIAL

		annotation SummarizationSetBy = Automatic

	column EMPRESA
		dataType: string
		lineageTag: 155a4881-247c-4736-a6e0-509367c7d0de
		summarizeBy: none
		sourceColumn: EMPRESA

		annotation SummarizationSetBy = Automatic

	column REPRESENTANTE
		dataType: string
		lineageTag: cb396e71-d561-4648-9748-eda261e4a1bd
		summarizeBy: none
		sourceColumn: REPRESENTANTE

		annotation SummarizationSetBy = Automatic

	column DIM_ITEM_ID
		dataType: string
		lineageTag: 9021a134-cc62-4282-b671-d8d76bfb5295
		summarizeBy: none
		sourceColumn: DIM_ITEM_ID

		annotation SummarizationSetBy = Automatic

	partition fPedido-24034e89-6c6d-42ea-a97d-3af7c3cf61e1 = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("BRPIN-DBS008\PowerBI", "idba_komatsu", [Query="SELECT #(lf)      A.DIM_COND_PAGTO_ID#(lf)      ,A.NR_PEDIDO#(lf)      ,CONCAT(E.DIM_ITEM_ID, ' - ', E.NM_ITEM) AS DIM_ITEM_ID#(lf)      ,A.DT_EMISSAO#(lf)      ,A.DT_ENTREGA#(lf)      ,A.NF_NUM#(lf)      ,A.TIPO#(lf)      ,A.POS_PDV#(lf)      ,A.QTDE#(lf)      ,A.QTDE_ATEND#(lf)      ,A.QTDE - A.QTDE_ATEND AS QTDE_EM_ABERTO#(lf)      ,A.QTDE_CANC#(lf)      ,A.QTDE_SLDO#(lf)      ,A.PRECO_UNIT#(lf)      ,A.VLR_BRUTO#(lf)      ,A.VLR_BRUTO_SICMS#(lf)      ,A.DIM_DIVISAO_VENDA_ID#(lf)      ,A.NF_SERIE#(lf)      ,A.NF_DATA#(lf)      ,A.PRIORIDADE#(lf)      ,A.NR_PEDIDO_CLIENTE#(lf)      ,A.NR_SEQ_PED#(lf)      ,A.NR_SEQ_PED_NF#(lf)      ,A.FATURAMENTO_PARCIAL#(lf)      ,A.VALOR_LIQUIDO_NF#(lf)      ,B.TP_DIVISAO_VENDA#(lf)      ,C.NM_UNID_NEGOC#(lf)      ,CONCAT(A.DIM_EMPRESA_ID, '_', A.DIM_ITEM_ID) AS IdPedidoSaldoEstoque#(lf)      ,CONCAT(A.NR_PEDIDO_CLIENTE, '-', A.NR_SEQ_PED,'-', A.DIM_ITEM_ID) AS ID_PEDIDO_SEQ_ITEM#(lf)      ,CONCAT(D.COD_CLIENTE, ' - ', D.CLIENTE) AS CLIENTE#(lf)      ,E.DESC_C1 AS FAMILIA_COMERCIAL#(lf)      ,CONCAT(F.DIM_EMPRESA_ID, ' - ', F.CIDADE) AS EMPRESA#(lf)      ,CONCAT(G.COD_REPRESENTANTE, ' - ', G.REPRESENTANTE) AS REPRESENTANTE#(lf)#(lf)  FROM [idba_komatsu].[dbo].[FATO_PEDIDO_BI] A#(lf)  INNER JOIN DIM_DIVISAO_VENDA_BI B ON A.DIM_DIVISAO_VENDA_ID = B.DIM_DIVISAO_VENDA_ID#(lf)  LEFT JOIN DIM_UNID_NEGOC_BI C ON C.COD_UNID_NEGOC = A.DIM_UNID_NEGOC_ID#(lf)  LEFT JOIN DIM_CLIENTE_BI D ON D.COD_CLIENTE = A.DIM_CLIENTE_ID#(lf)  LEFT JOIN DIM_ITEM_BI E ON E.CD_ITEM = A.DIM_ITEM_ID#(lf)  LEFT JOIN DIM_EMPRESA_BI F ON F.COD_EMPRESA = A.DIM_EMPRESA_ID#(lf)  LEFT JOIN DIM_REPRESENTANTE_BI G ON G.COD_REPRESENTANTE = A.DIM_REPRESENTANTE_ID#(lf)  WHERE B.TP_DIVISAO_VENDA IN ('PEÇAS','PEÇAS ATIVAS','PEÇAS KDB', 'PEÇAS CONTRATO')#(lf)  AND A.POS_PDV <> 'Cancelado'#(lf)  AND A.DT_EMISSAO > '01/01/2022'#(lf)  ORDER BY A.DT_EMISSAO DESC#(lf);"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{ {"DT_EMISSAO", type date}, {"DT_ENTREGA", type date}, {"NF_DATA", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

