table FSaldoEstoqueDiario
	lineageTag: 83e42f85-81fd-4b99-b7f9-281038e4d406

	column it-codigo
		dataType: string
		lineageTag: 34bc3619-0fed-4a5e-829c-0410891ebbee
		summarizeBy: none
		sourceColumn: it-codigo

		annotation SummarizationSetBy = Automatic

	column periodo
		dataType: dateTime
		formatString: Short Date
		lineageTag: b08316ff-50ba-4883-88ea-37ce3685b130
		summarizeBy: none
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column cod-estabel
		dataType: string
		lineageTag: 930eeb49-4a65-4175-8050-b8d3b07813ba
		summarizeBy: none
		sourceColumn: cod-estabel

		annotation SummarizationSetBy = Automatic

	column quantidade
		dataType: double
		lineageTag: 001e8ba0-7e4a-4a84-8947-e3650e9c0ee2
		summarizeBy: sum
		sourceColumn: quantidade

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IdPedidoSaldoEstoque
		dataType: string
		lineageTag: 74001262-9797-4509-8b0f-70c2727c3508
		summarizeBy: none
		sourceColumn: IdPedidoSaldoEstoque

		annotation SummarizationSetBy = Automatic

	column 'ITEM TRATADO'
		dataType: string
		lineageTag: 0cd578f1-7e23-4541-95af-4d79748b8e5f
		summarizeBy: none
		sourceColumn: ITEM TRATADO

		annotation SummarizationSetBy = Automatic

	column IdPedidoSaldoEstoqueItemTratado
		dataType: string
		lineageTag: ed53a744-0f0e-4372-9d79-a1816f97db42
		summarizeBy: none
		sourceColumn: IdPedidoSaldoEstoqueItemTratado

		annotation SummarizationSetBy = Automatic

	partition FSaldoEstoqueDiario = m
		mode: import
		source = ```
				let
				    Fonte = Sql.Database("10.105.40.196\powerbi", "idba_komatsu", [Query="select periodo, [cod-estabel], [it-codigo], sum(quantidade) as quantidade from FATO_SALDO_ESTOQUE_DIARIO#(lf)group by periodo,[it-codigo], [cod-estabel]"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"periodo", type date}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [periodo] >= #date(2022, 1, 1)),
				    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Filtradas", "IdPedidoSaldoEstoque", each [#"cod-estabel"]&[#"it-codigo"]),
				    #"Add Item Tratado" = Table.AddColumn(#"Personalização Adicionada", "ITEM TRATADO", each if Text.End([#"it-codigo"],6)="-USE-C" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-6)
				    else if Text.End([#"it-codigo"],5)="E-KI-" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-5)
				    else if Text.End([#"it-codigo"],5)="-KI-C" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-5)
				    else if Text.End([#"it-codigo"],5)="-USEC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-5)
				    else if Text.End([#"it-codigo"],5)="-LM-C" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-5)
				    else if Text.End([#"it-codigo"],4)="-USE" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="USEC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)	
				    else if Text.End([#"it-codigo"],4)="-XCC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="EKIC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="KI-C" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="-KIC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="-KI-" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="E-KI" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="-SUZ" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="-GAR" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="LM-C" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],4)="-LMC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-4)
				    else if Text.End([#"it-codigo"],3)="-XC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-3)
				    else if Text.End([#"it-codigo"],3)="LMC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-3)
				    else if Text.End([#"it-codigo"],3)="KIC" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-3)
				    else if Text.End([#"it-codigo"],3)="E-C" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-3)
					else if Text.End([#"it-codigo"],3)="-LM" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-3)
				    else if Text.End([#"it-codigo"],3)="-IM" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-3)
				    else if Text.End([#"it-codigo"],3)="-AB" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-3)
				    else if Text.End([#"it-codigo"],3)="-KI" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-3)
				    else if Text.End([#"it-codigo"],2)="-C" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-2)
				    else if Text.End([#"it-codigo"],2)="-E" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-2)
					else if Text.End([#"it-codigo"],1)="E" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-1)
					else if Text.End([#"it-codigo"],1)= "e"  then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-1)
				    else if Text.End([#"it-codigo"],1)="C" then Text.Start([#"it-codigo"],Text.Length([#"it-codigo"])-1)
				    else [#"it-codigo"]),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Add Item Tratado", "IdPedidoSaldoEstoqueItemTratado", each [#"cod-estabel"]&[ITEM TRATADO]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"IdPedidoSaldoEstoque", type text}, {"ITEM TRATADO", type text}, {"IdPedidoSaldoEstoqueItemTratado", type text}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado1",{{"periodo", Order.Descending}})
				in
				    #"Linhas Classificadas"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

